"$schema" = 'https://starship.rs/config-schema.json'

format = """
🧊 \
$all
"""

add_newline = true

palette = 'kanagawa'
command_timeout = 1000

[palettes.kanagawa]
color_fg0 = '#DCD7BA'
color_bg1 = '#1F1F28'
color_bg3 = '#2A2A37'
color_blue = '#7E9CD8'
color_cyan = '#6A9589'
color_green = '#76946A'
color_purple = '#957FB8'
color_red = '#C34043'
color_yellow = '#C0A36E'

[username]
show_always = false
style_user = "bold fg:color_purple"
style_root = "bold fg:color_purple"
format = '[$user ]($style)'

[character]
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
format = '$symbol  '

[package]
disabled = true

[battery]
disabled = true
